name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
