name: pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 5"

permissions: {}

jobs:
  pre-commit-autoupdate:
    name: pre-commit autoupdate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          body: This PR updates pre-commit hooks 🚀
          branch: pre-commit-autoupdate
          commit-message: Update pre-commit hooks
          delete-branch: true
          title: Update pre-commit hooks
