name: pre-commit autoupdate

on:
  schedule:
    - cron: "0 21 * * 5"
  pull_request:

permissions: {}

jobs:
  pre-commit-autoupdate:
    name: pre-commit autoupdate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run `pre-commit autoupdate`
        run: pre-commit autoupdate
